name: main

on:
  push:
    branches: 
      - "Server-IA"
      - "Front-end"
      - "Login"
      - "Registration"
      - "Search"
      - "authservice"
  pull_request:
    branches: 
      - "Server-IA"
      - "Front-end"
      - "Login"
      - "Registration"
      - "Search"
      - "authservice"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        default: 'github-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Run component tests
        run: npm run test
      - name: Setup Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/'
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/deploy-pages@v1
        with:
          environment: ${{ github.event.inputs.environment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
